services:
  - type: web
    name: omniload
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.12.0
