services:
  - type: web
    name: omniload-v2
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22.12.0"
